version: '3'

services:
  php:
    build: ./php
    container_name: php
    volumes:
      - ./src/backend:/var/www/html

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 18888:80
    volumes:
      - ./src/backend:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

#  mysql:
#    build: ./mysql
#    container_name: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: app
#      MYSQL_USER: user
#      MYSQL_PASSWORD: password
#      TZ: 'Asia/Tokyo'
#    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
#    ports:
#      - 13336:3306
#    volumes:
#      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
#      - ./db/mysql:/var/lib/mysql
#      - ./mysql/sql:/docker-entrypoint-initdb.d

  postgres:
    image: postgres:15-bullseye
    container_name: postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGPASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
      TZ: "Asia/Tokyo"
    ports:
      - 15432:5432
    volumes:
      - ./db/postgres:/var/lib/postgresql/data

  node:
    image: node:14.18-buster
    container_name: node
    tty: true
    volumes:
      - ./src/frontend:/var/www/html
    working_dir: /var/www/html

volumes:
  db:
